module.exports.User = require("./user.model"); 1
module.exports.Admin = require("./admin.model"); 11
module.exports.Restaurant = require("./restaurant.model"); 4
module.exports.Restauranttype = require("./restaurant_type.model"); 3
module.exports.Restaurantimage = require("./restaurant_image.route"); 5
module.exports.City = require("./city.model"); 10
module.exports.Country = require("./country.model"); 9
module.exports.State = require("./state.model"); 2
module.exports.Openinghours = require("./opening_hours.model"); 8
module.exports.Item = require("./item.model"); 12
module.exports.Menuitem = require("./menu_item.model"); 13
module.exports.Order = require("./order.model"); 7
module.exports.Orderitem = require("./order_item.model"); 14
module.exports.Cart = require("./cart.model"); 15
module.exports.Offer = require("./offer.model"); 16
module.exports.Offeritem = require("./offer_item.model"); 17
module.exports.Payment = require("./payment.model"); 6
module.exports.DeliveryAddresses = require("./delivery_addresses.model"); 18
module.exports.Deliverydrivers = require("./delivery_drivers.model"); 19
module.exports.Deliveries = require("./deliveries.model");20
module.exports.comment = require("./comment.model");
module.exports.Review = require("./review.model");
module.exports.Notification = require("./notification.model");